### ISSUE TITLE
Improve MS Teams support

### ISSUE THREAD

**Issue by MKletz** [DavideViolante/pr-reviews-reminder-action#1]
Would it be possible to add support for MS teams as well?

----------

edit by @DavideViolante:
- [x] MS Teams works
- [x] message with links
- [ ] mentions

**Comment by DavideViolante** [comment]
I think it would be possible since there are webhooks there. I'll try to work on that on my spare time. PRs are welcome

**Comment by MKletz** [comment]
I can try and poke at it. Never done JS before.

**Comment by DavideViolante** [comment]
Can you please be a beta tester for Teams? We use Slack at work so I cannot test it on Teams, but the code should work I think. Can you try to add this GitHub Action to your repository?

```yml
name: PRs reviews reminder

on:
  schedule:
    # Every weekday every 2 hours during working hours, send notification
    - cron: "0 8-17/2 * * 1-5"

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-reviews-reminder-action@microsoftteams
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: '<REPLACE_ME_HERE>' # Required
```

Replace the `<REPLACE_ME_HERE>` string with the Webhook of MS Teams, [more info about webhooks here](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
If you want replace the cron schedule to test it faster (eg: "* * * * *" will trigger every minute)
