### ISSUE TITLE
Allow a multiline github-provider-map value

### ISSUE THREAD

**Issue by mabaumgartner** [DavideViolante/pr-reviews-reminder-action#88]
For readability and maintainability as new colaborators are added, it would be great if the `github-provider-map` value could be a multiline YAML syntax such as:

```yml
name: PRs reviews reminder

on:
  schedule:
    # Every weekday every 2 hours during working hours, send notification
    - cron: "0 8-17/2 * * 1-5"

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-reviews-reminder-action@v2.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: '' # Required
        provider: '' # Required (slack or msteams)
        channel: '' # Optional, eg: #general
        ignore-label: '' # Optional, eg: no-reminder
        github-provider-map: >-
          git-user1:ms-user1@example.com,
          git-user2:msuser2@example.com,
          git-user3:msuser3@foo.com
```

I'm not familiar with JS syntax but might it be possible to remove spaces before splitting the string value?  
https://github.com/DavideViolante/pr-reviews-reminder-action/blob/master/functions.js#L67

Also potentially worth noting a related item for troubleshooting: if the syntax of the `github-provider-map` value is not in the correct format, the action output says a message was sent successfully but no message actually appears in a MSTeams channel.  Maybe a debug line could be added to help future adopters?
Thanks!
