### ISSUE TITLE
Error on empty github-provider-map

### ISSUE THREAD

**Issue by edthedev** [DavideViolante/pr-reviews-reminder-action#94]
Looks like `github-provider-map` is no longer effectively optional.
The default value of `false` gets sent through the provider map interpreter code and results in an error.

## Error output

```sh
Run DavideViolante/pr-reviews-reminder-action@v[2](https://github.com/techservicesillinois/secdev-template-repository/actions/runs/4107948173/jobs/7088054218#step:2:2).[3](https://github.com/techservicesillinois/secdev-template-repository/actions/runs/4107948173/jobs/7088054218#step:2:3).1
  with:
    webhook-url: ***
    provider: msteams
    channel: #general
    github-provider-map: false
  env:
    GITHUB_TOKEN: ***
Getting open pull requests...
There are 1 open pull requests and [4](https://github.com/techservicesillinois/secdev-template-repository/actions/runs/4107948173/jobs/7088054218#step:2:4) reviewers
There are 1 pull requests waiting for reviews
Error: The github-provider-map string is not in correct format: "name1:id1,name2:id2,..."
Notification sent successfully!
```

## To Reproduce

```yaml
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: DavideViolante/pr-reviews-reminder-action@v2.3.1
      with:
        webhook-url: ${{ secrets.TEAMS_WEBHOOK }}
        provider: 'msteams'
```
